spring:
  # 项目信息
  application:
    name: fruit    # 工程名
  profiles:
    active: dev    # 默认为开发环境
  # 数据库参数
  datasource:
    url: jdbc:mysql://localhost/demo2_admin
    username: techrice
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 阿里 Druid 数据库连接池配置
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

server:
  port: 8088    # 端口，不配置时默认为 8080

# mybatis-plus 配置
mybatis-plus:
  # 配置 xml 位置，默认为：classpath*:/mapper/**/*.xml
  mapper-locations: classpath*:/mapper/**Mapper.xml

# 日志相关配置
logging:
  level:
    root: info    # 根目录（所有），不配置时默认为 info
    com.example.admin.mapper: debug    # 配置 Mapper 层的日志等级，可看见生成的 SQL 语句

# JWT 配置
admin:
  jwt:
    header: Authorization    # 本项目会将 JWT 作为响应报文的首部字段的一行（header 作为 key : jwt 数据作为 value）
    expire: 604800           # 604800秒 = 7天
    secret: ji8n3439n439n43ld9ne9343fdfer49h    # 加密密钥
